AWSTemplateFormatVersion: 2010-09-09
Description: Automated deployment of QuickSight Assets.
Parameters:
  DestAccountID:
    Description: Account ID that needs to get access to the template (dest account)
    Type: String
  QSUser:
    Description: QS Username in Account ID where to own the template that will be created
    Type: String
  SrcQSAdminRegion:
    Description: "Admin region for your QS source account where your users are hosted"
    Type: String      
Resources:
  CICDQSTemplate:
    Type: 'AWS::QuickSight::Template'
    Properties:
      TemplateId: ''
      Name: ''
      AwsAccountId: 
        Ref: 'AWS::AccountId'
      SourceEntity:
        SourceAnalysis:
          Arn:
            Fn::Sub: 'arn:aws:quicksight:${AWS::Region}:${AWS::AccountId}:analysis/{analysis_id}'              
          DataSetReferences:
          - DataSetArn: 
                Fn::Sub: 'arn:aws:quicksight:${AWS::Region}:${AWS::AccountId}:dataset/{dataset_id}'                  
            DataSetPlaceholder: ''
                        
      Permissions:
        - Actions:
          - quicksight:DescribeTemplate
          - quicksight:UpdateTemplate
          - quicksight:DeleteTemplate
          - quicksight:UpdateTemplateAlias
          - quicksight:DescribeTemplatePermissions
          - quicksight:UpdateTemplatePermissions
          Principal: 
            Fn::Sub: 'arn:aws:quicksight:${SrcQSAdminRegion}:${AWS::AccountId}:user/default/${QSUser}'
        - Actions:
          - quicksight:DescribeTemplate
          - quicksight:DescribeTemplateAlias
          Principal: 
            Fn::Sub: 'arn:aws:iam::${DestAccountID}:root'              
      VersionDescription: Initial version - Copied over from AWS account.